import type { Metadata } from 'next';

import { ReactQueryProvider } from '../providers/reactQueryProvider';

import { ButtonTheme } from '@/components/buttonTheme';
import { ThemeProvider } from '@/components/themeProvider';

import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <html lang="pt-br" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="flex flex-col items-center h-[100vh]">
              <div className="flex  w-full h-[40%] justify-end p-12">
                <ButtonTheme />
              </div>

              {children}
            </main>
          </ThemeProvider>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
